[package]
name = "charlang"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
pest = "2.7"
pest_derive = "2.7"
serde = "1.0.219"
serde_json = "1.0.140"

